name:                peirabot
version:             0.1.0.0
github:              "wkirschbaum/peirabot"
license:             BSD3
author:              "Wilhelm Hugo Kirschbaum"
maintainer:          "wkirschbaum@gmail.com"
copyright:           "2018 Wilhelm Hugo Kirschbaum"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/peirabot#readme>

dependencies:
- base >= 4.7 && < 5
- time
- random

library:
  source-dirs: src
  exposed-modules:
    - Peirabot.Bot
    - Peirabot.Modules.Greet
    - Peirabot.Modules.Utilities
    - Peirabot.Modules.Quit

executables:
  peirabot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peirabot

tests:
  peirabot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peirabot
